version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db/postgres"
    env_file:
      - .env
    depends_on:
      - db
    command: [ "scripts/wait-for-it.sh", "db:5432", "--", "scripts/run-app.sh" ]
  db:
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./.cache/postgres-data:/var/lib/postgresql/data:cached
