version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run tests
          command: poetry run pytest --version
  publish-latest: 
      docker:
      - image: cimg/python:3.10.2
      steps: 
        - checkout
        - setup_remote_docker:
            docker_layer_caching: true
        - run: 
            name: Publish Docker Image to Docker Hub
            command: |
              TAG=0.1.$CIRCLE_BUILD_NUM
              docker build -t oxyyx/prdctr:$TAG .
              docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_ACCESS_KEY
              docker push oxyyx/prdctr:$TAG
              docker push oxyyx/prdctr:latest
workflows:
  main:
    jobs:
      - build-and-test
      - publish-latest:
          requires:
              - build-and-test