version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    resource_class: small
    docker:
      - image: cimg/python:3.10.2
        auth: 
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_ACCESS_KEY
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Create test-report directory
          command: mkdir test-report
      - run:
          name: Copy the .env.example to .env for the test run
          command: cp .env.example .env
      - run:
          name: Run tests
          command: poetry run pytest --junit-xml=test-report/report.xml
      - store_test_results:
          path: test-report
  publish-latest: 
      resource_class: small
      filters:
        brn
      docker:
      - image: cimg/python:3.10.2
      steps: 
        - checkout
        - setup_remote_docker:
            docker_layer_caching: true
        - run: 
            name: Publish Docker Image to Docker Hub
            command: |
              TAG=0.1.$CIRCLE_BUILD_NUM
              docker build -t oxyyx/prdctr:$TAG -t oxyyx/prdctr:latest .
              echo "$DOCKERHUB_ACCESS_KEY" | docker login -u $DOCKERHUB_USERNAME --password-stdin
              docker push oxyyx/prdctr --all-tags

workflows:
  main:
    jobs:
      - build-and-test
      - publish-latest:
          filters:
            branches:
              only: main
          requires:
              - build-and-test